[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
mdoc-reader-ffi = { git = "https://github.com/zhuolabs/mdoc-reader", rev = "919773b1270a45589908b9deb125515dfdd7e64c" }
mdoc-transport-ble = { git = "https://github.com/zhuolabs/mdoc-reader", rev = "919773b1270a45589908b9deb125515dfdd7e64c", features = ["uniffi"] }
nfc-reader = { git = "https://github.com/zhuolabs/mdoc-reader", rev = "919773b1270a45589908b9deb125515dfdd7e64c", features = ["uniffi"] }
mdoc-android-platform = { path = "crates/mdoc-android-platform" }
uniffi = { version = "=0.32.0" }

[profile.release]
lto = "thin"
strip = "debuginfo"
