package com.example.mdocreader

import android.Manifest
import android.bluetooth.BluetoothManager
import android.content.Intent
import android.content.pm.PackageManager
import java.io.FileNotFoundException
import android.nfc.NfcAdapter
import android.os.Bundle
import android.provider.Settings
import android.view.WindowManager
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.runtime.getValue
import androidx.core.content.ContextCompat
import androidx.lifecycle.lifecycleScope
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.example.mdocreader.rust.ReaderSession
import com.example.mdocreader.rust.BleHardware
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.MutableStateFlow
import com.example.mdocreader.theme.MdocReaderTheme

class MainActivity : ComponentActivity() {
    private val state = MutableStateFlow(ReaderState())
    private var nfcHardware: NfcSessionHardware? = null
    private var bleHardware: BleHardware? = null
    private var session: ReaderSession? = null
    private var reading: Job? = null
    private var generation = 0
    private val nfc by lazy { NfcAdapter.getDefaultAdapter(this) }
    private val permissions = arrayOf(Manifest.permission.BLUETOOTH_CONNECT, Manifest.permission.BLUETOOTH_ADVERTISE)
    private val requestPermissions = registerForActivityResult(ActivityResultContracts.RequestMultiplePermissions()) { result ->
        if (permissions.all { result[it] == true || ContextCompat.checkSelfPermission(this, it) == PackageManager.PERMISSION_GRANTED }) startRead()
        else state.value = ReaderState(error = "Nearby devices permission is required. Allow it in app settings and try again.")
    }
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        window.addFlags(WindowManager.LayoutParams.FLAG_SECURE)
        setContent {
            val current by state.collectAsStateWithLifecycle()
            MdocReaderTheme {
                ReaderScreen(current, ::requestRead, ::cancelRead,
                    { state.value = ReaderState() },
                    { startActivity(Intent(Settings.ACTION_WIRELESS_SETTINGS)) })
            }
        }
    }
    private fun requestRead() {
        if (reading?.isActive == true) return
        if (permissions.any { ContextCompat.checkSelfPermission(this, it) != PackageManager.PERMISSION_GRANTED }) {
            requestPermissions.launch(permissions); return
        }
        startRead()
    }
    @android.annotation.SuppressLint("MissingPermission")
    private fun startRead() {
        if (reading?.isActive == true) return
        val adapter = nfc
        if (adapter == null || !adapter.isEnabled) {
            state.value = ReaderState(error = "Turn on NFC. An NFC-capable device is required."); return
        }
        val bluetooth = getSystemService(BluetoothManager::class.java).adapter
        if (bluetooth == null || !bluetooth.isEnabled) {
            state.value = ReaderState(error = "Turn on Bluetooth to continue."); return
        }
        state.value = ReaderState(busy = true, stage = "certificate_loading")
        window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
        val thisGeneration = ++generation
        reading = lifecycleScope.launch {
            val eventSink = UiEventSink { event ->
                runOnUiThread { if (generation == thisGeneration && state.value.busy) state.value = state.value.copy(stage = event) }
            }
            val nfcSession = AndroidNfcHardware(this@MainActivity, adapter)
            val bleSession: BleHardware = AndroidBleHardware(this@MainActivity, eventSink)
            nfcHardware = nfcSession
            bleHardware = bleSession
            var native: ReaderSession? = null
            try {
                nfcSession.start()
                val request = withContext(Dispatchers.IO) { loadRequest() }
                native = ReaderSession(nfcSession, bleSession, eventSink)
                session = native
                // Generated by UniFFI as suspend fun; the Rust worker runs off Main.
                val result = native.read(request)
                val documents = withContext(Dispatchers.Default) { parseDocuments(result) }
                state.value = ReaderState(stage = "complete", documents = documents)
            } catch (e: CancellationException) {
                if (generation == thisGeneration) state.value = ReaderState(stage = "cancelled")
                throw e
            } catch (e: Exception) {
                state.value = ReaderState(error = e.message ?: "Reading failed")
            } catch (e: LinkageError) {
                state.value = ReaderState(error = "Cannot load the Rust library: ${e.message}")
            } finally {
                native?.cancel(); native?.close()
                nfcSession.shutdown(); bleSession.shutdown()
                nfcHardware = null; bleHardware = null; session = null
                window.clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
            }
        }
    }
    private fun loadRequest(): String {
        for (name in listOf("request.json", "request.example.json")) {
            try {
                return assets.open(name).bufferedReader().use { it.readText() }
            } catch (_: FileNotFoundException) {
                // A local request is optional; the tracked example is the fallback.
            }
        }
        error("No request JSON asset is available")
    }
    private fun cancelRead() {
        session?.cancel()
        nfcHardware?.shutdown()
        bleHardware?.shutdown()
        reading?.cancel()
    }
    override fun onStop() {
        ++generation
        cancelRead()
        state.value = ReaderState()
        super.onStop()
    }
}

