[package]
name = "mdoc-android"
version = "0.1.0"
edition = "2024"
[lib]
crate-type = ["cdylib", "rlib"]
[features]
btstack = ["dep:mdoc-transport-btstack", "dep:mdoc-android-platform", "dep:async-trait", "dep:tokio", "dep:nfc-reader", "dep:mdoc-transport-ble", "dep:anyhow"]

[dependencies]
uniffi.workspace = true
mdoc-reader-ffi.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
mdoc-transport-btstack = { path = "../mdoc-transport-btstack", optional = true }
mdoc-android-platform = { workspace = true, optional = true }
mdoc-transport-ble = { workspace = true, optional = true }
nfc-reader = { workspace = true, optional = true }
anyhow = { workspace = true, optional = true }
async-trait = { version = "0.1", optional = true }
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
