[package]
name = "mdoc-android"
version = "0.1.0"
edition = "2024"
[lib]
crate-type = ["cdylib", "rlib"]
[features]
btstack = ["dep:mdoc-transport-btstack"]

[target.'cfg(target_os = "android")'.dependencies]
mdoc-transport-btstack = { path = "../mdoc-transport-btstack", optional = true }

[dependencies]
anyhow.workspace = true
uniffi = { workspace = true, features = ["tokio"] }
mdoc-core.workspace = true
mdoc-reader-flow.workspace = true
mdoc-security.workspace = true
mdoc-ui.workspace = true
mdoc-android-platform.workspace = true
nfc-reader.workspace = true
mdoc-transport-ble.workspace = true
async-trait = "0.1"
mdoc-ui-android = { path = "../mdoc-ui-android" }
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
tokio = { version = "1", features = ["rt-multi-thread", "time", "net", "sync", "macros"] }
tokio-util = { version = "0.7", features = ["rt"] }

[dev-dependencies]
mdoc-transport.workspace = true
nfc-reader.workspace = true
tokio = { version = "1", features = ["test-util"] }
